# Generated by Django 4.2.3 on 2026-02-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"verbose_name": "Факультет", "verbose_name_plural": "Факультеты",},
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Тип материала",
                "verbose_name_plural": "Типы материала",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="news/images/", verbose_name="Изображение новость"
                    ),
                ),
                ("heading", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("text", models.TextField(max_length=5000, verbose_name="Текст")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Если галочка снята, новость не отображается на сайте",
                        verbose_name="Видимость",
                    ),
                ),
            ],
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости",},
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Подзаголовок"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("leftImg", "Изображение слева"),
                            ("rightImg", "Изображение справа"),
                            ("noImg", "Без изображения"),
                            ("btn", "Кнопка"),
                        ],
                        default="noImg",
                        max_length=20,
                        verbose_name="Тип параграфа",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="paragraphs/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, max_length=5000, verbose_name="Текст"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Если галочка снята, параграф не отображается на сайте",
                        verbose_name="Видимость",
                    ),
                ),
            ],
            options={"verbose_name": "Параграф", "verbose_name_plural": "Параграфы",},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
            ],
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты",},
        ),
        migrations.CreateModel(
            name="ProjectParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.paragraph"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_paragraphs",
                        to="main.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параграф проекта",
                "verbose_name_plural": "Параграфы проекта",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="paragraphs",
            field=models.ManyToManyField(
                through="main.ProjectParagraph",
                to="main.paragraph",
                verbose_name="Параграфы",
            ),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.PositiveSmallIntegerField(null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="Файл материалы",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="main.discipline",
                    ),
                ),
                (
                    "faculties",
                    models.ManyToManyField(
                        related_name="disciplines", to="main.faculty"
                    ),
                ),
                (
                    "material_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.materialtype",
                    ),
                ),
            ],
            options={"verbose_name": "Материал", "verbose_name_plural": "Материалы",},
        ),
    ]
