# Generated by Django 5.2.6 on 2025-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='url',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(null=True, upload_to='materials/', verbose_name='Файл материалы'),
        ),
    ]
