# Generated by Django 5.2.6 on 2025-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_material_url_material_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='faculty',
        ),
        migrations.AddField(
            model_name='discipline',
            name='faculties',
            field=models.ManyToManyField(related_name='disciplines', to='main.faculty'),
        ),
    ]
