# Generated by Django 5.2.6 on 2025-09-17 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_course_year_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='faculties',
        ),
        migrations.AddField(
            model_name='material',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.discipline'),
        ),
        migrations.AddField(
            model_name='material',
            name='faculties',
            field=models.ManyToManyField(related_name='disciplines', to='main.faculty'),
        ),
        migrations.AddField(
            model_name='material',
            name='semester',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
