# Generated by Django 5.2.6 on 2025-09-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_material_course_remove_discipline_faculties_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'Тип материала', 'verbose_name_plural': 'Типы материала'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
